---
title: "R Project 1 - Hello R"
author: "Azfar Vahidy"
date: "1/23/2020"
output: html_document
---

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1

The datasaurus dozen file has 1846 rows and 3 columns. The variables included are dataset,x, and y.

### Exercise 2

Plotting Dino Data

```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

Calculating correlation coefficient

```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3

Plotting Star Data

```{r plot-star}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

Calculating correlation coefficient

```{r cor-star}
star_data %>%
  summarize(r = cor(x, y))
```

### Exercise 4

Plotting Circle Data

```{r}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

Calculating correlation coefficient

```{r}
circle_data %>%
  summarize(r = cor(x, y))
```

### Exercise 5

```{r}
```